apiVersion : apps/v1
kind: Deployment
metadata:
  name: bathiniarundotnetarun 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bathiniarundotnetarun
  template:
    metadata:
      labels:
        app: bathiniarundotnetarun 
    spec:
      containers:
        - name: bathiniarundotnetarun 
          image: dotnet1.azurecr.io/bathiniarundotnetarun:1
          ports:
          - containerPort: 8080
