apiVersion: v1
kind: Service
metadata:
  name: bathiniarundotnetarun
  namespace: speed
spec:
  selector:
    app: bathiniarundotnetarun
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
