apiVersion: v1
kind: Service
metadata:
    name: bathiniarundotnetarun
spec:
    type: LoadBalancer
    ports:
    port: 80          # The port to access the service
    selector:
        app: bathiniarundotnetarun
