apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbullrace
  namespace: default
  labels:
    app: redbull
spec:
  selector:
    matchLabels:
      app: redbull
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redbull
    spec:
      serviceAccountName: default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: user
                  operator: In
                  values:
                    - arun
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redbull
              topologyKey: "kubernetes.io/hostname"  # Assuming "kubernetes.io/hostname" is a valid node label key.
      tolerations:
        - key: "haas"
          operator: "Equal"
          value: "10"
          effect: "NoSchedule"
      containers:
        - name: redbull
          image: arunbachi/b1:1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: redbull
                  key: DB_HOST
          ports:
            - containerPort: 80
              name: redbull
